### Deployment ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api-deployment
  labels:
    app: chat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      containers:
        - name: chat-api
          image: agulinari/chat-api:1.0.0
          ports:
            - containerPort: 8080
