### Service ####
apiVersion: v1
kind: Service
metadata:
  name: chat-api-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: chat-api
  type: NodePort